---
- name: Install Docker on Debian
  hosts: development
  become: true
  tasks:
    - name: Install required packages
      ansible.builtin.package:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present

    - name: Create Docker GPG key directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Install Docker packages
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
        state: present

    - name: Add user to docker group
      ansible.builtin.user:
        name: ivanipani
        groups: docker
        append: true

    - name: Ensure Docker service is running and enabled
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

- name: Install Minikube
  hosts: development
  become: true
  tasks:

    - name: Create Minikube directory
      ansible.builtin.file:
        path: /usr/local/bin/minikube
        state: directory
        mode: '0755'
    - name: Download Minikube
      ansible.builtin.get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
        dest: /usr/local/bin/minikube
        mode: '0644'

    - name: Install Minikube
      ansible.builtin.apt:
        deb: /usr/local/bin/minikube/minikube_latest_amd64.deb
        state: present

- name: Install kubectl
  hosts: poochella
  become: true
  tasks:


    - name: Create Docker GPG key directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Kubernetes GPG key
      ansible.builtin.get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.33/deb/Release.key
        dest: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        mode: '0644'

    - name: Add Kubernetes repository
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.33/deb/ /
        state: present
        filename: kubernetes

    - name: Install Kubernetes packages
      ansible.builtin.apt:
        name:
          - kubectl
        state: present
